### ISSUE TITLE
error: use of '@import' when C++ modules are disabled

### ISSUE THREAD

**Issue by CobreDev** [Randomblock1/theos-action#1]
I'm pretty new to GitHub Actions, so I don't know much about them.

When I try to set this up with [BlurHider](https://github.com/CobreDev/BlurHider), it gives me `BlurHider.xm:3:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules`

As far as I can tell, I'm using the iOS 14.4 SDK from the Theos SDKs repo.
What am I doing wrong?

**Comment by Randomblock1** [comment]
I don't know, this is just a wrapper for Theos. It builds my tweak fine, and all it does is install Theos, compiling is up to you. It seems like you might have to add flags to the Makefile? I really don't know, you might want to ask around in the Discord.

**Comment by CobreDev** [comment]
Ok, i'll try building it normally and go from there. Thanks!
