### ISSUE TITLE
Swift toolchain might need updating

### ISSUE THREAD

**Issue by jackmthws** [Randomblock1/theos-action#3]
~~HI! Unfortunately Orion doesn't work with this action anymore and I think itSwift 5.6+. This could be solved by updating to a toolchain from https://github.com/kabiroberai/swift-toolchain-linux/releases :)~~

Not too sure why Orion support isn't working, but I think it's to do with the toolchain - see this workflow run https://github.com/vendetta-mod/VendettaTweak/actions/runs/4101898008/jobs/7074204552

**Comment by Randomblock1** [comment]
I've updated the toolchain, should work now

**Comment by Randomblock1** [comment]
Fixed in v1.3
